cc_library(
    name = "autos",
    srcs = [
        "drive_auto.cc",
        "scoring_auto.cc",
        "balance_auto.cc"
    ],
    hdrs = [
        "drive_auto.h",
        "scoring_auto.h",
        "balance_auto.h"
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//Offseason2910Clone:field",
        "//Offseason2910Clone/commands",
    ],
)
