cc_library(
    name = "autos",
    srcs = [
        "scoring_two_piece_auto_command.cc",
        "alliance_two_piece_auto_command.cc",
        "alliance_two_piece_dock_auto_command.cc",
        "mid_one_piece_dock_auto_command.cc",
        "mid_one_piece_pickup_dock_auto_command.cc",
        "drive_auto.cc",
    ],
    hdrs = [
        "scoring_two_piece_auto_command.h",
        "alliance_two_piece_auto_command.h",
        "alliance_two_piece_dock_auto_command.h",
        "mid_one_piece_dock_auto_command.h",
        "mid_one_piece_pickup_dock_auto_command.h",
        "drive_auto.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//y2023:field",
        "//y2023/commands",
    ],
)
