cc_library(
    name = "wpilib",
    srcs = [
        "time.cc",
    ],
    hdrs = [
        "time.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//transitionLib846",
        "@bazelrio//libraries/cpp/wpilib/wpilibc",
    ],
)
